// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoHpntryS9HruV3Os-AAGOFuklzIo-vZg',
    appId: '1:405358281418:web:3a732dfe2eaaed53eeea33',
    messagingSenderId: '405358281418',
    projectId: 'test-flutter-92f17',
    authDomain: 'test-flutter-92f17.firebaseapp.com',
    storageBucket: 'test-flutter-92f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByAXCaPSg6eP9G8E_TXBjTUuYhD34xis4',
    appId: '1:405358281418:android:c5eaf81207b4d40feeea33',
    messagingSenderId: '405358281418',
    projectId: 'test-flutter-92f17',
    storageBucket: 'test-flutter-92f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmKlN7-k8fHjtpzz28C5kW6oeptHkzltk',
    appId: '1:405358281418:ios:60c5b4d15ac95a64eeea33',
    messagingSenderId: '405358281418',
    projectId: 'test-flutter-92f17',
    storageBucket: 'test-flutter-92f17.appspot.com',
    iosBundleId: 'com.example.flutterDay1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmKlN7-k8fHjtpzz28C5kW6oeptHkzltk',
    appId: '1:405358281418:ios:5e224d7510998b76eeea33',
    messagingSenderId: '405358281418',
    projectId: 'test-flutter-92f17',
    storageBucket: 'test-flutter-92f17.appspot.com',
    iosBundleId: 'com.example.flutterDay1.RunnerTests',
  );
}
